#!/bin/bash
#===============================================================================
# Lobster Container Init — runs once at systemd boot as a oneshot service
#
# Responsibilities:
#   1. Write config.env from environment variables injected by docker-compose.
#      The docker-compose env_file (config.staging.env) sets TELEGRAM_BOT_TOKEN,
#      LOBSTER_ENV, etc. — this script materialises them into the file that the
#      lobster systemd services load via EnvironmentFile=.
#
#   2. Run install.sh --container-setup for runtime setup:
#      - Creates runtime directories and symlinks
#      - Verifies sqlite-vec loads correctly
#      - Creates stub user-config agent files
#      - Seeds canonical memory templates (idempotent)
#      - Writes ~/.claude/settings.json with all hooks (self-contained — no host
#        .claude bind-mount required)
#
#   3. Verify MCP registration in settings.json.
#      settings.json is generated by install.sh --container-setup, so registration
#      should always be present. This step is a safety net for edge cases (e.g.
#      a persistent workspace volume that pre-dates this change).
#
# This script runs as the lobster user (see lobster-container-init.service).
# It must complete before lobster-router/lobster-claude/lobster-mcp-local start.
#===============================================================================

set -euo pipefail

LOBSTER_DIR="/home/lobster/lobster"
WORKSPACE_DIR="/home/lobster/lobster-workspace"
MESSAGES_DIR="/home/lobster/messages"
CONFIG_DIR="/home/lobster/lobster-config"
LOG_DIR="$WORKSPACE_DIR/logs"

export PATH="/home/lobster/.local/bin:/usr/local/bin:/usr/bin:/bin"

echo "[container-init] Starting..."

#-------------------------------------------------------------------------------
# 1. Write config.env from environment variables
#
# docker-compose env_file injects TELEGRAM_BOT_TOKEN, LOBSTER_ENV, etc. into
# the container environment. The lobster systemd services load config.env via
# EnvironmentFile=, so we materialise the runtime values here.
#
# LOBSTER_ENV must be "production" — the dispatcher exits immediately if it is
# not. The staging config.staging.env.example documents this requirement.
#-------------------------------------------------------------------------------
mkdir -p "$CONFIG_DIR"
LOG_FILE="$LOG_DIR/container-init.log"
mkdir -p "$LOG_DIR"

# Always overwrite config.env from environment variables on every boot.
# A skip-if-exists guard here caused a production outage: when config.staging.env
# changed (e.g. a new TELEGRAM_BOT_TOKEN), the persistent volume still held the
# old config.env and the container silently used stale values. config.env is cheap
# to regenerate — always write it from the injected environment.
echo "[container-init] Writing config.env from environment..."
cat > "$CONFIG_DIR/config.env" << CONFIG
# Lobster Staging Config — generated by lobster-container-init.sh
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}
LOBSTER_ADMIN_CHAT_ID=${LOBSTER_ADMIN_CHAT_ID:-${TELEGRAM_ALLOWED_USERS:-}}
LOBSTER_ENV=${LOBSTER_ENV:-production}
LOBSTER_DEBUG=${LOBSTER_DEBUG:-false}
GITHUB_TOKEN=${GITHUB_TOKEN:-}
# ^ Set in config.staging.env to enable gh CLI inside the container.
#   Not inherited from host environment (see docker-compose for details).
CONFIG
echo "[container-init] config.env written."

#-------------------------------------------------------------------------------
# 2. Run install.sh --container-setup
#
# Idempotent — safe to run on every boot. Handles:
#   - sqlite-vec load verification
#   - CLAUDE.md and .claude/ symlinks
#   - Stub user-config agent files
#   - Canonical memory template seeding
#   - lobster-state.json seeding with booted_at
#   - ~/.claude/settings.json with all hooks (makes the image self-contained)
#-------------------------------------------------------------------------------
echo "[container-init] Running install.sh --container-setup..."
LOBSTER_INSTALL_DIR="$LOBSTER_DIR" \
LOBSTER_WORKSPACE="$WORKSPACE_DIR" \
LOBSTER_MESSAGES="$MESSAGES_DIR" \
LOBSTER_CONFIG_DIR="$CONFIG_DIR" \
    bash "$LOBSTER_DIR/install.sh" --container-setup 2>&1 | tee -a "$LOG_FILE" || true
echo "[container-init] Container setup complete."

#-------------------------------------------------------------------------------
# 3. Verify MCP registration in settings.json
#
# install.sh --container-setup writes settings.json with all hooks.
# The Dockerfile also pre-registers the MCP server via `claude mcp add`.
# This step is a safety net: if the workspace volume already has an older
# settings.json that pre-dates the hooks (e.g. from a previous container run),
# register the MCP server to ensure it is present.
#-------------------------------------------------------------------------------
SETTINGS_FILE="/home/lobster/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
    if ! python3 -c "import json; d=json.load(open('$SETTINGS_FILE')); exit(0 if 'lobster-inbox' in str(d) else 1)" 2>/dev/null; then
        echo "[container-init] MCP registration not found in settings.json — registering..."
        /home/lobster/.local/bin/claude mcp add --transport http lobster-inbox \
            -s user http://localhost:8766/mcp 2>/dev/null || true
    else
        echo "[container-init] MCP registration present — skipping."
    fi
fi

echo "[container-init] Done."
